version: "2"

services:
  scan:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:${PWD}/sonar/conf
      - sonarqube_data:${PWD}/sonar/data
      - sonarqube_extensions:${PWD}/sonar/extensions
      - sonarqube_bundled-plugins:${PWD}/sonar/bundled-plugins

  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:${PWD}/postgresql
      - postgresql_data:${PWD}/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data: